// PRODUCT VARIABLES (Strings, Numbers, Booleans)

let product1 = "Smart Watch X1";
let price1 = 59;
let available1 = true;

let product2 = "Wireless Headphones";
let price2 = 39;
let available2 = true;

let product3 = "Casual Hoodie";
let price3 = 29;
let available3 = false;

let product4 = "Sports Shoes";
let price4 = 49;
let available4 = true;

let product5 = "Gaming Mouse";
let price5 = 25;
let available5 = true;

let product6 = "Summer T-Shirt";
let price6 = 19;
let available6 = false;

// LOG TO CONSOLE
console.log("Product List:");
console.log(product1, price1, available1);
console.log(product2, price2, available2);
console.log(product3, price3, available3);
console.log(product4, price4, available4);
console.log(product5, price5, available5);
console.log(product6, price6, available6);

